### ISSUE TITLE
Does the configuration of SS now allow forecast-year fecundity to be different from final year?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#496]
p23 of 2018 assessment we said
```
set forecast-year fecundity (including 2017 due to current configurations
in Stock Synthesis) weight-at-age to the product of maturity and mean
weight-at-age over 2015-2017
```

Since Chris and I did not have 2018 data, we assumed 2018 weight-at-age and fecundity to be means from 2015-2017. This serendipitiously avoided the configuration issue. 

But now we plan to have 2018 age data, does the 'configuration' issue mean that we cannot use 2018 weight-at-age and fecundity for 2018, but the 2016-2018 means for the projections?

However, if SS is updated somehow, am thinking it's a bit late to be using a new version, as things always seem to break.

(Related to #492).

**Comment by taylori** [comment]
I forgot about this issue.
Yes, the combination of that text in the document and looking the wtatage.ss file for the alternative fecundity model where the true 2017 weight-at-age is commented out with the note
`# 2017 and forecast is based on avg. wt over 2015:2017`
convinces me that it wasn't possible to input a separate forecast weight-at-age at that time.

This may have been corrected in more recent versions of SS, but that brings up the need to do a comparison of the versions to see if anything else has changed. I don't remember if there have been changes that would impact the model results, but thinking about it now, I remember that there have definitely been a few formatting changes that would likely break the compilation, so it's probably best at this stage to not change executables, even if this problem of forecast weight-at-age has been corrected.

That raises the question of whether it's better to use the 2016-2018 average for 2018 and the forecast, or to input the true 2018 values and use the longer-term average (entered in the -1940 row) for the forecast. I don't have any strong opinions on which is best. I suspect the differences would be pretty small.

**Comment by aaronmberger** [comment]
For now I have it set to long term average for equilibrium and early year wt-at-age and fecundity and have used 2018 empirical data so forecast will be based on long-term average also.

**Comment by andrew-edwards** [comment]
Okay. Chris will be happy that we're not updating SS3!

1. This only affects fecundities, yes? 

2. And so only when time-varying?

Think we have the combination of sensitivites to help cover this, will just have to tweak some of them. Differences do seem small.

I'm off now (text me if necessary tonight, doubt needed though).

**Comment by andrew-edwards** [comment]
@aaronmberger  - maybe give that a dummy model number then, as it doesn't sound like a simple extension of our current base case.

We were assuming that you'd start with our `2019.02.00_base_model` and edit that to make the new one. Otherwise it'll get confusing. 

We can chat tomorrow if necessary to clarify (realise that you guys are still getting caught up - just that the structure we've built will really help for adding the age data, but only in the way we envisioned)...

**Comment by taylori** [comment]
Looks like the alternative model from last year shows the same issue was present for both the fecundity matrix and all the weight-at-age matrices.
To estimate the status of the stock at the beginning of 2019, it would be more accurate to use the true 2018 weight-at-age and the long-term average in the forecast.
To make the forecast as accurate as possible, it would be better to use the 2016-2018 average for 2018 as well as the forecast.

Regardless, the weight-at-age data from 2018 is unlikely to have anywhere near as big an impact as the age composition data, so simplest first step would be to leave the wtatage.ss file alone with no 2018 weights, add age comps and see how big a change that makes. Then create new model numbers as @andrew-edwards suggests for the additional changes of either option to add 2018 weight-at-age (in addition to the other changes to the weight-at-age matrix like the inclusion of more Canadian samples)

**Comment by aaronmberger** [comment]
Let's milestone this thread for 2020 so as to not forget (like we would) about this new version of SS and that we will have to do an SS version bridge and that forecast year wt-at-age and fecundity-at-age can be independent of the last empirical year.

**Comment by cgrandin** [comment]
For sure. There's no time to deal with it at this point.

**Comment by kellijohnson-NOAA** [comment]
Kelli is emailing Rick.

**Comment by aaronmberger-nwfsc** [comment]
also referenced in #523

**Comment by kellijohnson-NOAA** [comment]
No it doesn't, says Rick. But, he is willing to change the tpl. If Rick doesn't have time to do it before January I am sure that Ian and I can modify the tpl so Rick just has to approve the change. Is this something we want/need for this year?

**Comment by kellijohnson-NOAA** [comment]
I investigated some more, and the capability is there to set any values different than the average. You must specify all forecast years though because it won't propagate them going forward. So, if you don't want an average calculated by SS you must specify all 3 forecast years to be the values you want. 
Sensitivities to include:
 - [ ] values averaged over all years
 - [ ] average of last five years, where selectivity is also averaged over last five years

**Comment by andrew-edwards** [comment]
@kellijohnson-NOAA - last year we did projections as average fecundity of the last three years. New text says we used the last five years. (I'm trying to compare which model run from last year we are most similar to). I forget (but I think we discussed it) why we're doing five?
I first read the second checkbox in the above comment to mean 'do five instead of three years', but now I'm a bit confused.... Thanks!

**Comment by andrew-edwards** [comment]
I think we're most like Run 54 from last year, except we can now use the real data for the final year and have it different from the forecast years (the subject of this issue).

**Comment by andrew-edwards** [comment]
- [ ] Comment out MCMC fecundity appendix.
- [ ] Remove equilibrium assumption (10 years) sensitivity runs as MLEs 
- [ ] Update text in data.rnw
- [ ] Check text in sens section

**Comment by andrew-edwards** [comment]
@cgranding - this is what you were just doing. But assigned to me.
